print("welcome to San's mad libs. You are going to have a bad time.")
name = raw_input("what is your name: ")
noun1 = raw_input("give me a noun: ")
noun2 = raw_input("give me a noun: ")
noun3 = raw_input("give me a noun: ")
adjective1 = raw_input("give me a adjective 'ly': ")
adjective2 = raw_input("give me a adjective ending in 'ly' : ")
verb1 = raw_input("give me a verb: ")
verb2 = raw_input("give me a verb: ")
num1 = int(raw_input("give me a number: "))
print(name + " enjoys " + noun1 + " and eating " + noun3 + " very " + adjective1 + ". " + " While eating their " + noun3 + " they like to " + adjective2 + verb1 + " while " + verb2 + str(num1) + " times. ")
